### ISSUE TITLE
Healthcare Industry text spills over into banner (Android 10)

### ISSUE THREAD

**Issue by tdk2fe** [ocelotconsulting/ocelot.github.io#17]
The text is obstructed by the top level graphic

![image](https://user-images.githubusercontent.com/632530/81848936-6f2b8480-951b-11ea-9a23-b4ee6925b9bf.png)

**Comment by tdk2fe** [comment]
Actually this seems to happen on a lot of the pages...

![image](https://user-images.githubusercontent.com/632530/81849142-b9146a80-951b-11ea-9fae-342b1cc7259b.png)

**Comment by jiangdev** [comment]
https://github.com/ocelotconsulting/ocelot.github.io/pull/26 should fix this issue

**Comment by jiangdev** [comment]
fixed by https://github.com/ocelotconsulting/ocelot.github.io/pull/26
