### ISSUE TITLE
Blog posts have no margins - iphone X

### ISSUE THREAD

**Issue by johnomalley** [ocelotconsulting/ocelot.github.io#6]
![image](https://user-images.githubusercontent.com/933065/81817541-7db17600-94f2-11ea-925b-173a0a52ec9d.png)

**Comment by johnomalley** [comment]
This is probably not critical

**Comment by patrickrgaffney** [comment]
Fixed in #11. ![image](https://user-images.githubusercontent.com/7366232/81856111-ed8d2400-9525-11ea-8c96-acac6c505e32.png)
